import type { Patient, TriageLevel, PatientLocation } from './types.js';

export const samplePatients: Patient[] = [
	{
		id: '1',
		surname: 'Smith',
		forename: 'John',
		age: 45,
		gender: 'M',
		nhsNumber: '943 476 5919',
		department: 'Majors',
		location: 'trolley' as PatientLocation,
		arrivalTime: '2026-03-16T08:15:00',
		triageLevel: 2 as TriageLevel,
		alerts: ['Falls risk'],
		allergies: ['Penicillin'],
		chiefComplaint: 'Chest pain',
		hasDuplicateName: false,
	},
	{
		id: '2',
		surname: 'Smyth',
		forename: 'Jon',
		age: 72,
		gender: 'M',
		nhsNumber: '612 883 2041',
		department: 'Majors',
		location: 'trolley' as PatientLocation,
		arrivalTime: '2026-03-16T09:02:00',
		triageLevel: 1 as TriageLevel,
		alerts: ['Dementia', 'DNR'],
		allergies: [],
		chiefComplaint: 'Shortness of breath',
		hasDuplicateName: false,
	},
	{
		id: '3',
		surname: 'Patel',
		forename: 'Priya',
		age: 28,
		gender: 'F',
		nhsNumber: '438 291 7753',
		department: 'Minors',
		location: 'waiting_room' as PatientLocation,
		arrivalTime: '2026-03-16T09:30:00',
		triageLevel: 4 as TriageLevel,
		alerts: [],
		allergies: ['Latex'],
		chiefComplaint: 'Sprained ankle',
		hasDuplicateName: false,
	},
	{
		id: '4',
		surname: 'Williams',
		forename: 'Emma',
		age: 56,
		gender: 'F',
		nhsNumber: '765 432 1098',
		department: 'Resus',
		location: 'resus' as PatientLocation,
		arrivalTime: '2026-03-16T07:45:00',
		triageLevel: 1 as TriageLevel,
		alerts: ['Epilepsy'],
		allergies: ['Aspirin', 'Ibuprofen'],
		chiefComplaint: 'Seizure',
		hasDuplicateName: false,
	},
	{
		id: '5',
		surname: 'Jones',
		forename: 'David',
		age: 34,
		gender: 'M',
		nhsNumber: '321 654 9870',
		department: 'Minors',
		location: 'consultation_room' as PatientLocation,
		arrivalTime: '2026-03-16T10:12:00',
		triageLevel: 5 as TriageLevel,
		alerts: [],
		allergies: [],
		chiefComplaint: 'Laceration to hand',
		hasDuplicateName: false,
	},
	{
		id: '6',
		surname: 'O\'Brien',
		forename: 'Sarah',
		age: 81,
		gender: 'F',
		nhsNumber: '198 765 4320',
		department: 'Majors',
		location: 'trolley' as PatientLocation,
		arrivalTime: '2026-03-16T08:50:00',
		triageLevel: 3 as TriageLevel,
		alerts: ['Falls risk', 'Hearing impaired'],
		allergies: ['Codeine'],
		chiefComplaint: 'Abdominal pain',
		hasDuplicateName: false,
	},
	{
		id: '7',
		surname: 'Khan',
		forename: 'Ali',
		age: 19,
		gender: 'M',
		nhsNumber: '555 123 4567',
		department: 'Minors',
		location: 'waiting_room' as PatientLocation,
		arrivalTime: '2026-03-16T10:45:00',
		triageLevel: 4 as TriageLevel,
		alerts: [],
		allergies: [],
		chiefComplaint: 'Sore throat',
		hasDuplicateName: false,
	},
	{
		id: '8',
		surname: 'Davies',
		forename: 'Margaret',
		age: 67,
		gender: 'F',
		nhsNumber: '876 543 2109',
		department: 'Majors',
		location: 'ambulance' as PatientLocation,
		arrivalTime: '2026-03-16T09:15:00',
		triageLevel: 2 as TriageLevel,
		alerts: ['Diabetes'],
		allergies: ['Sulfonamides'],
		chiefComplaint: 'Confusion',
		hasDuplicateName: false,
	},
];
